name: Deploy to Cloud Run and Firebase Hosting

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: flowcraft-95bf4
  REGION: us-central1
  SERVICE_NAME: flowcraft-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_BACKEND_URL: https://flowcraft-api-329437257912.us-central1.run.app/api
      VITE_FIREBASE_API_KEY: AIzaSyBT8_iF5_CqsDgd-owIKWcj-tg9aUA9nD8
      VITE_FIREBASE_AUTH_DOMAIN: flowcraft-95bf4.firebaseapp.com
      VITE_FIREBASE_PROJECT_ID: flowcraft-95bf4
      VITE_FIREBASE_STORAGE_BUCKET: flowcraft-95bf4.firebasestorage.app
      VITE_FIREBASE_MESSAGING_SENDER_ID: "725841371789"
      VITE_FIREBASE_APP_ID: "1:725841371789:web:358bdb65cc85986a0fb8c4"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # --- Server Deployment (Cloud Run) ---
      - name: Build and Push Container
        run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/flowcraft/${{ env.SERVICE_NAME }} ./server
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/flowcraft/${{ env.SERVICE_NAME }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/flowcraft/${{
            env.SERVICE_NAME }}
          flags: "--allow-unauthenticated --port=8080"
          env_vars: |-
            GOOGLE_GEMINI_API_KEY=${{ secrets.GOOGLE_GEMINI_API_KEY }}
            GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
            FIREBASE_PROJECT_ID=${{ env.PROJECT_ID }}
            FIREBASE_SERVICE_ACCOUNT_JSON=${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
            ALLOWED_ORIGINS=https://${{ env.PROJECT_ID }}.web.app,https://${{ env.PROJECT_ID }}.firebaseapp.com

      # --- Client Deployment (Firebase Hosting) ---
      - name: Install Client Dependencies
        run: npm install
        working-directory: ./client

      - name: Build Client
        run: npm run build
        working-directory: ./client

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.GCP_SA_KEY }}
          channelId: live
          projectId: ${{ env.PROJECT_ID }}
